import type { NextPage } from "next";
import Head from "next/head";
import Landing from "../components/Landing";

const Home: NextPage = () => {
  return (
    <div className="h-full">
      <Head>
        <title>March</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <Landing />
      </div>
    </div>
  );
};

export default Home;
